package com.example.demo.service;

import com.example.demo.dto.CategoryStat;
import com.example.demo.model.Activity;
import com.example.demo.model.User;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;

@Service
public class ExportService {

    private static final DateTimeFormatter DATE = DateTimeFormatter.ISO_DATE;
    private static final Color BRAND = new Color(46, 125, 50);

    private final ActivityService activityService;
    private final DashboardService dashboardService;

    public ExportService(ActivityService activityService, DashboardService dashboardService) {
        this.activityService = activityService;
        this.dashboardService = dashboardService;
    }

    /** All of a user's activities as a CSV byte array. */
    public byte[] activitiesCsv(User user) {
        List<Activity> activities = activityService.listFor(user);
        StringBuilder sb = new StringBuilder();
        sb.append("Date,Type,Category,Amount,Unit,CO2_kg,Note\n");
        for (Activity a : activities) {
            sb.append(a.getDate().format(DATE)).append(',')
              .append(csv(a.getType().getLabel())).append(',')
              .append(csv(a.getType().getCategory().getLabel())).append(',')
              .append(a.getAmount()).append(',')
              .append(a.getType().getUnit()).append(',')
              .append(a.getCo2Kg()).append(',')
              .append(csv(a.getNote())).append('\n');
        }
        return sb.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);
    }

    private String csv(String value) {
        if (value == null) {
            return "";
        }
        if (value.contains(",") || value.contains("\"") || value.contains("\n")) {
            return '"' + value.replace("\"", "\"\"") + '"';
        }
        return value;
    }

    /** A styled PDF summary report for the given user. */
    public byte[] summaryReport(User user) {
        Document document = new Document(PageSize.A4, 48, 48, 54, 48);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            PdfWriter.getInstance(document, out);
            document.open();

            Font title = new Font(Font.HELVETICA, 22, Font.BOLD, BRAND);
            Font heading = new Font(Font.HELVETICA, 13, Font.BOLD, Color.DARK_GRAY);
            Font normal = new Font(Font.HELVETICA, 11, Font.NORMAL, Color.BLACK);
            Font muted = new Font(Font.HELVETICA, 9, Font.ITALIC, Color.GRAY);

            Paragraph header = new Paragraph("EchoTracker — Carbon Report", title);
            document.add(header);
            document.add(new Paragraph(
                    "Prepared for " + displayName(user) + " on " + LocalDate.now().format(DATE), muted));
            document.add(Chunk.NEWLINE);

            document.add(new Paragraph("Summary", heading));
            document.add(new Paragraph(String.format(Locale.US,
                    "Total footprint (all time): %.2f kg CO2e", dashboardService.totalAllTime(user)), normal));
            document.add(new Paragraph(String.format(Locale.US,
                    "This month: %.2f kg CO2e", dashboardService.totalThisMonth(user)), normal));
            document.add(Chunk.NEWLINE);

            document.add(new Paragraph("By category", heading));
            List<CategoryStat> breakdown = dashboardService.categoryBreakdown(user);
            if (breakdown.isEmpty()) {
                document.add(new Paragraph("No activities logged yet.", normal));
            } else {
                PdfPTable table = new PdfPTable(3);
                table.setWidthPercentage(100);
                table.setSpacingBefore(6);
                addHeaderCell(table, "Category");
                addHeaderCell(table, "CO2e (kg)");
                addHeaderCell(table, "Share");
                for (CategoryStat stat : breakdown) {
                    table.addCell(cell(stat.label(), normal));
                    table.addCell(cell(String.format(Locale.US, "%.2f", stat.co2Kg()), normal));
                    table.addCell(cell(stat.percent() + "%", normal));
                }
                document.add(table);
            }

            document.add(Chunk.NEWLINE);
            document.add(new Paragraph(
                    "Generated by EchoTracker. Factors are estimates; tune them in application.properties.",
                    muted));
            document.close();
        } catch (DocumentException e) {
            throw new IllegalStateException("Failed to generate PDF report", e);
        }
        return out.toByteArray();
    }

    private String displayName(User user) {
        return user.getFullName() != null ? user.getFullName() : user.getUsername();
    }

    private void addHeaderCell(PdfPTable table, String text) {
        Font white = new Font(Font.HELVETICA, 11, Font.BOLD, Color.WHITE);
        PdfPCell cell = new PdfPCell(new Phrase(text, white));
        cell.setBackgroundColor(BRAND);
        cell.setPadding(6);
        table.addCell(cell);
    }

    private PdfPCell cell(String text, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setPadding(5);
        return cell;
    }
}
